import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Available languages across SwasthyaSetu
enum AppLanguage {
  english('en', 'English', 'en-IN'),
  marathi('mr', 'मराठी (Marathi)', 'mr-IN'),
  hindi('hi', 'हिन्दी (Hindi)', 'hi-IN'),
  telugu('te', 'తెలుగు (Telugu)', 'te-IN'),
  tamil('ta', 'தமிழ் (Tamil)', 'ta-IN'),
  kannada('kn', 'ಕನ್ನಡ (Kannada)', 'kn-IN'),
  gujarati('gu', 'ગુજરાતી (Gujarati)', 'gu-IN'),
  bengali('bn', 'বাংলা (Bengali)', 'bn-IN');

  final String code;
  final String label;
  final String speechLocale;

  const AppLanguage(this.code, this.label, this.speechLocale);

  static AppLanguage fromCode(String code) {
    return AppLanguage.values.firstWhere(
      (l) => l.code.toLowerCase() == code.toLowerCase() || l.name.toLowerCase() == code.toLowerCase(),
      orElse: () => AppLanguage.english,
    );
  }

  static AppLanguage fromLabel(String label) {
    return AppLanguage.values.firstWhere(
      (l) => l.label == label || l.name == label || l.code == label,
      orElse: () => AppLanguage.english,
    );
  }
}

/// Universal App Localization Service (Reactive ChangeNotifier Singleton)
class AppLocalizationService extends ChangeNotifier {
  static final AppLocalizationService _instance = AppLocalizationService._internal();
  static AppLocalizationService get instance => _instance;

  AppLocalizationService._internal() {
    _loadSavedLanguage();
  }

  AppLanguage _currentLanguage = AppLanguage.english;
  AppLanguage get currentLanguage => _currentLanguage;

  String get languageCode => _currentLanguage.code;
  String get speechLocale => _currentLanguage.speechLocale;

  Future<void> _loadSavedLanguage() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final code = prefs.getString('app_selected_language');
      if (code != null) {
        _currentLanguage = AppLanguage.fromCode(code);
        notifyListeners();
      }
    } catch (_) {}
  }

  Future<void> setLanguage(AppLanguage language) async {
    if (_currentLanguage == language) return;
    _currentLanguage = language;
    notifyListeners();
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('app_selected_language', language.code);
    } catch (_) {}
  }

  /// Translate a given key into current language
  String t(String key) {
    final langMap = _translations[_currentLanguage.code];
    if (langMap != null && langMap.containsKey(key)) {
      return langMap[key]!;
    }
    // Fallback to English
    final enMap = _translations['en'];
    if (enMap != null && enMap.containsKey(key)) {
      return enMap[key]!;
    }
    return key;
  }

  // Master translation dictionary for Indian languages
  static final Map<String, Map<String, String>> _translations = {
    // -------------------------------------------------------------
    // ENGLISH (en)
    // -------------------------------------------------------------
    'en': {
      // Platform & Shell
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'PHC-Centred Healthcare Access Platform (Maharashtra)',
      'switch_portal': 'Switch Portal',
      'emergency_sos': '108 EMERGENCY SOS',
      'logout': 'Logout',
      'language': 'Language',
      'live_gps_chip': 'Live GPS Active',
      'status_live': 'LIVE',

      // Navigation
      'nav_patient_home': 'Patient Home',
      'nav_my_consultations': 'My Consultations',
      'nav_hospital_referrals': 'Hospital Referrals',
      'nav_voice_checker': 'Voice Symptom Checker',
      'nav_opd_appointments': 'OPD Appointments',
      'nav_teleconsultation': 'Teleconsultation',
      'nav_emergency_alerts': 'Emergency Alerts',
      'nav_clinical_kpi': 'Clinical KPI & Telemetry',
      'nav_voice_symptoms': 'Voice Symptoms',
      'nav_patients_followups': 'Patients & Follow-ups',
      'nav_alerts_visits': 'Alerts & Visits',
      'nav_phc_overview': 'Facility & OPD Queue',
      'nav_phc_analytics': 'District Analytics',
      'nav_phc_asha_network': 'ASHA Network',
      'nav_phc_doctors': 'Medical Staff',
      'nav_pharmacy_dispense': 'Dispense Rx',
      'nav_pharmacy_inventory': 'Live Inventory',
      'nav_lab_orders': 'Diagnostic Orders',
      'nav_lab_tests': 'Test Catalog',

      // Roles
      'role_patient': 'Patient Portal',
      'role_doctor': 'Doctor Portal',
      'role_asha': 'ASHA Worker Portal',
      'role_phc_admin': 'PHC Administration',
      'role_pharmacy': 'PHC Pharmacy',
      'role_lab': 'PHC Diagnostics Lab',

      // Patient Portal
      'welcome_patient': 'Welcome back,',
      'live_gps_title': 'LIVE PATIENT GPS LOCATION (MAHARASHTRA)',
      'gps_detected_label': 'Live Detected GPS Position',
      'gps_coordinates': 'Coordinates',
      'gps_accuracy': 'GPS Accuracy',
      'btn_fetch_live_gps': 'Detect Live GPS',
      'btn_switch_district': 'Change Maharashtra District',
      'gps_status_active': 'Live GPS Tracking Active',
      'gps_status_detecting': 'Querying Device GPS Hardware...',
      'quick_actions': 'Healthcare Quick Actions',
      'find_medicines': 'Find Nearby Medicines',
      'find_medicines_sub': 'Check live stock at Shivaji Nagar PHC & Jan Aushadhi Stores',
      'book_lab_test': 'Book Diagnostic Test',
      'book_lab_test_sub': 'Free blood tests & diagnostics under NHM Maharashtra',
      'voice_ai_checker': 'AI Voice Symptom Checker',
      'voice_ai_checker_sub': 'Speak symptoms in Marathi, Hindi, Telugu, or English',
      'call_teleconsult': 'Call Doctor / Teleconsult',
      'call_teleconsult_sub': 'Direct video & audio consult with on-duty Medical Officer',
      'active_appointments': 'My Consultations & Appointments',
      'no_active_appointments': 'No upcoming doctor appointments scheduled.',
      'book_opd_now': 'Book OPD Appointment Now',
      'medical_records': 'My ABHA Health Records',
      'view_rx': 'View Doctor\'s Prescription (Rx)',
      'recent_vitals': 'Recent Recorded Vitals',
      'bp_label': 'Blood Pressure',
      'pulse_label': 'Pulse / Heart Rate',
      'spo2_label': 'Blood Oxygen (SpO2)',
      'temp_label': 'Body Temperature',

      // Doctor Portal
      'doc_opd_queue': 'Doctor OPD & Voice Triage Queue',
      'doc_teleconsult_title': 'Teleconsultation & Video Hub',
      'doc_alerts_title': 'Clinical Red-Flag Alerts',
      'doc_stats_title': 'Clinical Telemetry & Analytics',
      'add_prescription': 'Write Prescription',
      'refer_patient': 'Refer to Specialist',
      'start_video_consult': 'Start Jitsi Video Call',
      'patient_queue_no': 'Queue #',
      'symptoms_label': 'Symptoms',
      'diagnosis_label': 'Clinical Diagnosis',
      'advice_label': 'Medical Advice',
      'prescribed_drugs': 'Prescribed Medications',
      'receiving_facility': 'Receiving Facility / Hospital',
      'urgency_level': 'Urgency Level',
      'reason_referral': 'Reason for Referral',

      // ASHA Portal
      'asha_voice_title': 'Record Patient Voice Note',
      'asha_patients_title': 'Assigned Village Patients',
      'asha_alerts_title': 'Emergency Alerts & Village Triage',
      'register_new_patient': 'Register New Patient',
      'assigned_village': 'Assigned Village / Ward',
      'abha_id': 'ABHA Health ID',
      'patient_phone': 'Phone Number',
      'patient_name': 'Patient Full Name',
      'submit_triage': 'Run Clinical Voice Triage',
      'speak_symptoms': 'Tap to Speak Patient Symptoms',

      // Common
      'status_completed': 'Completed',
      'status_pending': 'Pending',
      'status_emergency': 'EMERGENCY',
      'status_urgent': 'URGENT',
      'status_routine': 'ROUTINE',
      'btn_refresh': 'Refresh',
      'btn_save': 'Save & Submit',
      'btn_cancel': 'Cancel',
      'btn_close': 'Close',
      'btn_search': 'Search',
      'filter_all': 'All',
      'filter_pending': 'Pending',
      'filter_prescribed': 'Prescribed',
      'filter_emergency': 'Emergency',
      'district_pune': 'Pune',
      'district_mumbai': 'Mumbai',
      'district_nagpur': 'Nagpur',
      'district_nashik': 'Nashik',
      'district_aurangabad': 'Chhatrapati Sambhaji Nagar',
      'district_kolhapur': 'Kolhapur',
      'district_satara': 'Satara',
      'district_thane': 'Thane',

      // Patient Service Cards
      'patient_services_title': 'ALL PATIENT SERVICES',
      'nearby_healthcare_title': 'NEARBY HEALTHCARE AVAILABILITY (MAHARASHTRA)',
      'svc_report_symptoms': 'Report Symptoms',
      'svc_report_symptoms_sub': 'Text-based clinical intake',
      'svc_voice_report': 'Voice Report',
      'svc_voice_report_sub': 'Speech-to-text with Whisper AI',
      'svc_book_appt': 'Book Appointment',
      'svc_book_appt_sub': 'OPD slot at Shivaji Nagar PHC',
      'svc_my_appts': 'My Appointments',
      'svc_my_appts_sub': 'View upcoming consultations',
      'svc_queue': 'Queue Status',
      'svc_queue_sub': 'Track live waiting time & number',
      'svc_records': 'My Health Records',
      'svc_records_sub': 'ABHA & consent-authorized',
      'svc_rx': 'Prescriptions',
      'svc_rx_sub': 'Doctor Rx & medication advice',
      'svc_lab': 'Lab Results',
      'svc_lab_sub': 'CBC, Malaria, diagnostic reports',
      'svc_referrals': 'Referrals & Follow-ups',
      'svc_referrals_sub': 'Specialist & routine check-ins',
      'svc_teleconsult': 'Teleconsultation',
      'svc_teleconsult_sub': 'WebRTC video room with doctor',
      'svc_medicines': 'Nearby Medicines',
      'svc_medicines_sub': 'Live pharmacy stock & pricing',
      'svc_diagnostics': 'Nearby Diagnostics',
      'svc_diagnostics_sub': 'Labs, tests & turnaround time',
      'svc_emergency_assist': 'Emergency Assistance',
      'svc_emergency_assist_sub': '108 Dispatch & ASHA Alert',
      'medicine_availability': 'Medicine Availability',
      'medicine_availability_sub': 'Find stock in nearby pharmacies',
      'diagnostic_centres': 'Nearby Diagnostic Centres',
      'diagnostic_centres_sub': 'NABL Labs & PHC Pathology',
      'check_medicine_stock': 'Check Medicine Stock',
      'find_diagnostic_centres': 'Find Diagnostic Centres',
      'ai_safety_notice': 'AI-assisted suggestion only — does not diagnose. Confirmed by a licensed clinician.',
      'appt_booked_snackbar': 'Appointment slot booked for 10:30 AM with Dr. Rajesh Sharma.',
    },

    // -------------------------------------------------------------
    // MARATHI (mr) — मराठी (Official language of Maharashtra)
    // -------------------------------------------------------------
    'mr': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'प्राथमिक आरोग्य केंद्र-केंद्रित आरोग्य सेवा मंच (महाराष्ट्र)',
      'switch_portal': 'पोर्टल बदला',
      'emergency_sos': '१०८ आपत्कालीन रुग्णवाहिका (SOS)',
      'logout': 'लॉग आउट',
      'language': 'भाषा',
      'live_gps_chip': 'थेट GPS स्थान सक्रिय',
      'status_live': 'थेट चालू',

      'nav_patient_home': 'रुग्ण मुख्यपृष्ठ',
      'nav_my_consultations': 'माझे सल्लामसलत',
      'nav_hospital_referrals': 'रुग्णालय संदर्भ (रेफरल)',
      'nav_voice_checker': 'व्हॉइस लक्षण तपासक',
      'nav_opd_appointments': 'ओपीडी भेटी',
      'nav_teleconsultation': 'टेलिकन्सल्टेशन (व्हिडिओ कॉल)',
      'nav_emergency_alerts': 'आपत्कालीन सतर्कता',
      'nav_clinical_kpi': 'क्लिनिकल आकडेवारी व टेलिमेट्री',
      'nav_voice_symptoms': 'व्हॉइस लक्षणे नोंदवा',
      'nav_patients_followups': 'रुग्ण आणि पाठपुरावा',
      'nav_alerts_visits': 'गाव सतर्कता आणि गृहभेटी',
      'nav_phc_overview': 'पीएचसी सुविधा आणि ओपीडी रांग',
      'nav_phc_analytics': 'जिल्हा आरोग्य विश्लेषण',
      'nav_phc_asha_network': 'आशा सेविका नेटवर्क',
      'nav_phc_doctors': 'वैद्यकीय कर्मचारी',
      'nav_pharmacy_dispense': 'औषध वितरण',
      'nav_pharmacy_inventory': 'थेट औषध साठा',
      'nav_lab_orders': 'निदान चाचणी मागण्या',
      'nav_lab_tests': 'प्रयोगशाळा कॅटलॉग',

      'role_patient': 'रुग्ण पोर्टल',
      'role_doctor': 'डॉक्टर पोर्टल',
      'role_asha': 'आशा सेविका पोर्टल',
      'role_phc_admin': 'पीएचसी प्रशासन',
      'role_pharmacy': 'पीएचसी औषधालय',
      'role_lab': 'पीएचसी निदान प्रयोगशाळा',

      'welcome_patient': 'स्वागत आहे,',
      'live_gps_title': 'रुग्णाचे थेट GPS स्थान (महाराष्ट्र)',
      'gps_detected_label': 'थेट शोधलेले GPS स्थान',
      'gps_coordinates': 'अक्षांश-रेखांश',
      'gps_accuracy': 'GPS अचूकता',
      'btn_fetch_live_gps': 'थेट GPS स्थान शोधा',
      'btn_switch_district': 'महाराष्ट्रातील जिल्हा बदला',
      'gps_status_active': 'थेट GPS ट्रॅकिंग सुरू आहे',
      'gps_status_detecting': 'डिव्हाइस GPS शोधत आहे...',
      'quick_actions': 'आरोग्य जलद सेवा',
      'find_medicines': 'जवळपासची औषधे शोधा',
      'find_medicines_sub': 'शिवाजी नगर पीएचसी आणि जन औषधी केंद्रातील थेट औषध साठा तपासा',
      'book_lab_test': 'निदान चाचणी बुक करा',
      'book_lab_test_sub': 'एनएचएम महाराष्ट्र अंतर्गत मोफत रक्त चाचण्या',
      'voice_ai_checker': 'एआय व्हॉइस लक्षण तपासक',
      'voice_ai_checker_sub': 'मराठी, हिंदी किंवा इंग्रजीत लक्षणे बोला',
      'call_teleconsult': 'डॉक्टरांशी थेट व्हिडिओ सल्ला',
      'call_teleconsult_sub': 'कर्तव्यावर असलेल्या वैद्यकीय अधिकाऱ्याशी थेट संपर्क',
      'active_appointments': 'माझ्या ओपीडी भेटी आणि सल्लामसलत',
      'no_active_appointments': 'कोणतीही आगामी ओपीडी भेट नियोजित नाही.',
      'book_opd_now': 'आताच ओपीडी भेट बुक करा',
      'medical_records': 'माझे आभा (ABHA) आरोग्य रेकॉर्ड',
      'view_rx': 'डॉक्टरांचे प्रिस्क्रिप्शन (Rx) पहा',
      'recent_vitals': 'अलीकडील तपासलेली जीवन चिन्हे',
      'bp_label': 'रक्तदाब (BP)',
      'pulse_label': 'नाडीचे ठोके (Pulse)',
      'spo2_label': 'रक्तातील ऑक्सिजन (SpO2)',
      'temp_label': 'शरीराचे तापमान',

      'doc_opd_queue': 'डॉक्टर ओपीडी आणि व्हॉइस ट्रायज रांग',
      'doc_teleconsult_title': 'टेलिकन्सल्टेशन आणि व्हिडिओ केंद्र',
      'doc_alerts_title': 'क्लिनिकल गंभीर धोक्याच्या सूचना',
      'doc_stats_title': 'क्लिनिकल आकडेवारी व टेलिमेट्री',
      'add_prescription': 'प्रिस्क्रिप्शन लिहा',
      'refer_patient': 'तज्ज्ञ रुग्णालयात रेफर करा',
      'start_video_consult': 'जित्सी व्हिडिओ कॉल सुरू करा',
      'patient_queue_no': 'रांग क्रमांक #',
      'symptoms_label': 'लक्षणे',
      'diagnosis_label': 'वैद्यकीय निदान',
      'advice_label': 'वैद्यकीय सल्ला',
      'prescribed_drugs': 'दिलेली औषधे',
      'receiving_facility': 'संदर्भ रुग्णालय (महाराष्ट्र)',
      'urgency_level': 'तातडीची पातळी',
      'reason_referral': 'रेफर करण्याचे कारण',

      'asha_voice_title': 'रुग्णांची व्हॉइस नोंदणी',
      'asha_patients_title': 'गावातील नियुक्त रुग्ण',
      'asha_alerts_title': 'आपत्कालीन सतर्कता आणि गाव ट्रायज',
      'register_new_patient': 'नवीन रुग्णाची नोंदणी करा',
      'assigned_village': 'नेमून दिलेले गाव / प्रभाग',
      'abha_id': 'आभा आरोग्य आयडी',
      'patient_phone': 'फोन नंबर',
      'patient_name': 'रुग्णाचे पूर्ण नाव',
      'submit_triage': 'क्लिनिकल व्हॉइस ट्रायज सुरू करा',
      'speak_symptoms': 'रुग्णाची लक्षणे बोलण्यासाठी टॅप करा',

      'status_completed': 'पूर्ण झाले',
      'status_pending': 'प्रलंबित',
      'status_emergency': 'तातडीचे / आपत्कालीन',
      'status_urgent': 'अतितातडीचे',
      'status_routine': 'नेहमीचे',
      'btn_refresh': 'रिफ्रेश करा',
      'btn_save': 'जतन करा आणि पाठवा',
      'btn_cancel': 'रद्द करा',
      'btn_close': 'बंद करा',
      'btn_search': 'शोधा',
      'filter_all': 'सर्व',
      'filter_pending': 'प्रलंबित',
      'filter_prescribed': 'प्रिस्क्रिप्शन दिले',
      'filter_emergency': 'आपत्कालीन',
      'district_pune': 'पुणे',
      'district_mumbai': 'मुंबई',
      'district_nagpur': 'नागपूर',
      'district_nashik': 'नाशिक',
      'district_aurangabad': 'छत्रपती संभाजीनगर',
      'district_kolhapur': 'कोल्हापूर',
      'district_satara': 'सातारा',
      'district_thane': 'ठाणे',

      // Patient Service Cards
      'patient_services_title': 'सर्व रुग्ण सेवा',
      'nearby_healthcare_title': 'जवळपासची आरोग्य सेवा (महाराष्ट्र)',
      'svc_report_symptoms': 'लक्षणे नोंदवा',
      'svc_report_symptoms_sub': 'लिखित क्लिनिकल माहिती',
      'svc_voice_report': 'व्हॉइस रिपोर्ट',
      'svc_voice_report_sub': 'व्हिस्पर AI सह बोलणे-ते-मजकूर',
      'svc_book_appt': 'भेट बुक करा',
      'svc_book_appt_sub': 'शिवाजी नगर पीएचसी येथे OPD स्लॉट',
      'svc_my_appts': 'माझ्या भेटी',
      'svc_my_appts_sub': 'आगामी सल्लामसलत पहा',
      'svc_queue': 'रांग स्थिती',
      'svc_queue_sub': 'थेट प्रतीक्षा वेळ आणि क्रमांक',
      'svc_records': 'माझे आरोग्य रेकॉर्ड',
      'svc_records_sub': 'ABHA आणि संमती-अधिकृत',
      'svc_rx': 'प्रिस्क्रिप्शन',
      'svc_rx_sub': 'डॉक्टरांचे Rx आणि औषध सल्ला',
      'svc_lab': 'प्रयोगशाळा निकाल',
      'svc_lab_sub': 'CBC, मलेरिया, निदान अहवाल',
      'svc_referrals': 'रेफरल आणि पाठपुरावा',
      'svc_referrals_sub': 'तज्ज्ञ आणि नियमित तपासणी',
      'svc_teleconsult': 'टेलिकन्सल्टेशन',
      'svc_teleconsult_sub': 'डॉक्टरसह WebRTC व्हिडिओ खोली',
      'svc_medicines': 'जवळपासची औषधे',
      'svc_medicines_sub': 'थेट फार्मसी साठा व किंमत',
      'svc_diagnostics': 'जवळपासचे निदान केंद्र',
      'svc_diagnostics_sub': 'लॅब, चाचण्या आणि टर्नअराउंड वेळ',
      'svc_emergency_assist': 'आपत्कालीन मदत',
      'svc_emergency_assist_sub': '108 एम्बुलन्स आणि आशा सतर्कता',
      'medicine_availability': 'औषध उपलब्धता',
      'medicine_availability_sub': 'जवळच्या फार्मसीमध्ये साठा शोधा',
      'diagnostic_centres': 'जवळचे निदान केंद्र',
      'diagnostic_centres_sub': 'NABL लॅब आणि पीएचसी पॅथॉलॉजी',
      'check_medicine_stock': 'औषध साठा तपासा',
      'find_diagnostic_centres': 'निदान केंद्रे शोधा',
      'ai_safety_notice': 'AI-सहाय्यित सूचना — निदान करत नाही. परवानाधारक डॉक्टरांनी पुष्टी केलेली.',
      'appt_booked_snackbar': 'डॉ. राजेश शर्मा यांच्याकडे सकाळी 10:30 वाजता भेट बुक झाली.',
    },

    // -------------------------------------------------------------
    // HINDI (hi) — हिन्दी
    // -------------------------------------------------------------
    'hi': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'प्राथमिक स्वास्थ्य केंद्र-केंद्रित स्वास्थ्य सेवा मंच (महाराष्ट्र)',
      'switch_portal': 'पोर्टल बदलें',
      'emergency_sos': '१०८ आपातकालीन एम्बुलेंस (SOS)',
      'logout': 'लॉग आउट',
      'language': 'भाषा',
      'live_gps_chip': 'लाइव GPS स्थान सक्रिय',
      'status_live': 'लाइव',

      'nav_patient_home': 'रोगी मुख्य पृष्ठ',
      'nav_my_consultations': 'मेरा परामर्श',
      'nav_hospital_referrals': 'अस्पताल रेफरल',
      'nav_voice_checker': 'ध्वनि लक्षण परीक्षक',
      'nav_opd_appointments': 'ओपीडी अपॉइंटमेंट',
      'nav_teleconsultation': 'टेलीकंसल्टेशन (वीडियो कॉल)',
      'nav_emergency_alerts': 'आपातकालीन अलर्ट',
      'nav_clinical_kpi': 'नैदानिक सांख्यिकी व टेलीमेट्री',
      'nav_voice_symptoms': 'आवाज से लक्षण दर्ज करें',
      'nav_patients_followups': 'रोगी एवं फॉलो-अप',
      'nav_alerts_visits': 'ग्राम अलर्ट और गृह भ्रमण',
      'nav_phc_overview': 'पीएचसी सुविधा एवं ओपीडी कतार',
      'nav_phc_analytics': 'जिला स्वास्थ्य विश्लेषण',
      'nav_phc_asha_network': 'आशा नेटवर्क',
      'nav_phc_doctors': 'चिकित्सा कर्मचारी',
      'nav_pharmacy_dispense': 'दवा वितरण',
      'nav_pharmacy_inventory': 'लाइव दवा स्टॉक',
      'nav_lab_orders': 'जांच आदेश',
      'nav_lab_tests': 'प्रयोगशाला कैटलॉग',

      'role_patient': 'रोगी पोर्टल',
      'role_doctor': 'डॉक्टर पोर्टल',
      'role_asha': 'आशा कार्यकर्ता पोर्टल',
      'role_phc_admin': 'पीएचसी प्रशासन',
      'role_pharmacy': 'पीएचसी फार्मेसी',
      'role_lab': 'पीएचसी डायग्नोस्टिक लैब',

      'welcome_patient': 'स्वागत है,',
      'live_gps_title': 'मरीज का लाइव GPS स्थान (महाराष्ट्र)',
      'gps_detected_label': 'लाइव खोजा गया GPS स्थान',
      'gps_coordinates': 'अक्षांश-देशांतर',
      'gps_accuracy': 'GPS सटीकता',
      'btn_fetch_live_gps': 'लाइव GPS स्थान पता करें',
      'btn_switch_district': 'महाराष्ट्र का जिला बदलें',
      'gps_status_active': 'लाइव GPS ट्रैकिंग सक्रिय है',
      'gps_status_detecting': 'डिवाइस GPS खोज रहा है...',
      'quick_actions': 'त्वरित स्वास्थ्य सेवाएँ',
      'find_medicines': 'निकटतम दवाइयाँ खोजें',
      'find_medicines_sub': 'शिवाजी नगर पीएचसी और जन औषधि केंद्र में लाइव स्टॉक देखें',
      'book_lab_test': 'डायग्नोस्टिक टेस्ट बुक करें',
      'book_lab_test_sub': 'एनएचएम महाराष्ट्र के तहत निःशुल्क रक्त परीक्षण',
      'voice_ai_checker': 'एआई वॉइस लक्षण परीक्षक',
      'voice_ai_checker_sub': 'हिंदी, मराठी या अंग्रेजी में लक्षण बोलें',
      'call_teleconsult': 'डॉक्टर से सीधे वीडियो परामर्श',
      'call_teleconsult_sub': 'ऑन-ड्यूटी मेडिकल ऑफिसर से तुरंत बातचीत',
      'active_appointments': 'मेरे परामर्श और अपॉइंटमेंट',
      'no_active_appointments': 'कोई आगामी अपॉइंटमेंट निर्धारित नहीं है।',
      'book_opd_now': 'अभी ओपीडी अपॉइंटमेंट बुक करें',
      'medical_records': 'मेरे आभा (ABHA) स्वास्थ्य रिकॉर्ड',
      'view_rx': 'डॉक्टर का नुस्खा (Rx) देखें',
      'recent_vitals': 'हाल ही में मापे गए वाइटल्स',
      'bp_label': 'रक्तचाप (BP)',
      'pulse_label': 'नाड़ी (Pulse)',
      'spo2_label': 'ऑक्सीजन (SpO2)',
      'temp_label': 'शरीर का तापमान',

      'doc_opd_queue': 'डॉक्टर ओपीडी और वॉइस ट्राइएज कतार',
      'doc_teleconsult_title': 'टेलीकंसल्टेशन और वीडियो हब',
      'doc_alerts_title': 'गंभीर आपातकालीन अलर्ट',
      'doc_stats_title': 'नैदानिक सांख्यिकी व टेलीमेट्री',
      'add_prescription': 'नुस्खा (प्रिस्क्रिप्शन) लिखें',
      'refer_patient': 'विशेषज्ञ अस्पताल रेफर करें',
      'start_video_consult': 'जित्सी वीडियो कॉल शुरू करें',
      'patient_queue_no': 'कतार क्रमांक #',
      'symptoms_label': 'लक्षण',
      'diagnosis_label': 'नैदानिक निदान',
      'advice_label': 'चिकित्सीय सलाह',
      'prescribed_drugs': 'निर्धारित दवाएं',
      'receiving_facility': 'रेफरल अस्पताल (महाराष्ट्र)',
      'urgency_level': 'आपातकालीन स्तर',
      'reason_referral': 'रेफरल का कारण',

      'asha_voice_title': 'मरीज की आवाज में लक्षण रिकॉर्ड करें',
      'asha_patients_title': 'गाँव के पंजीकृत मरीज',
      'asha_alerts_title': 'आपातकालीन अलर्ट और गाँव ट्राइएज',
      'register_new_patient': 'नया मरीज पंजीकृत करें',
      'assigned_village': 'आवंटित गाँव / वार्ड',
      'abha_id': 'आभा स्वास्थ्य पहचान पत्र',
      'patient_phone': 'फोन नंबर',
      'patient_name': 'मरीज का पूरा नाम',
      'submit_triage': 'क्लिनिकल वॉइस ट्राइएज चलाएं',
      'speak_symptoms': 'मरीज के लक्षण बोलने के लिए टैप करें',

      'status_completed': 'पूर्ण',
      'status_pending': 'लंबित',
      'status_emergency': 'आपातकालीन',
      'status_urgent': 'अति-आवश्यक',
      'status_routine': 'सामान्य',
      'btn_refresh': 'रिफ्रेश करें',
      'btn_save': 'सुरक्षित करें और सबमिट करें',
      'btn_cancel': 'रद्द करें',
      'btn_close': 'बंद करें',
      'btn_search': 'खोजें',
      'filter_all': 'सभी',
      'filter_pending': 'लंबित',
      'filter_prescribed': 'दवा निर्धारित',
      'filter_emergency': 'आपातकालीन',
      'district_pune': 'पुणे',
      'district_mumbai': 'मुंबई',
      'district_nagpur': 'नागपुर',
      'district_nashik': 'नासिक',
      'district_aurangabad': 'छत्रपति संभाजीनगर',
      'district_kolhapur': 'कोल्हापुर',
      'district_satara': 'सतारा',
      'district_thane': 'ठाणे',

      // Patient Service Cards
      'patient_services_title': 'सभी रोगी सेवाएँ',
      'nearby_healthcare_title': 'निकटतम स्वास्थ्य सेवाएँ (महाराष्ट्र)',
      'svc_report_symptoms': 'लक्षण रिपोर्ट करें',
      'svc_report_symptoms_sub': 'पाठ-आधारित क्लिनिकल रिपोर्ट',
      'svc_voice_report': 'वॉइस रिपोर्ट',
      'svc_voice_report_sub': 'Whisper AI से बोलकर टेक्स्ट',
      'svc_book_appt': 'अपॉइंटमेंट बुक करें',
      'svc_book_appt_sub': 'शिवाजी नगर PHC में OPD स्लॉट',
      'svc_my_appts': 'मेरी अपॉइंटमेंट',
      'svc_my_appts_sub': 'आगामी परामर्श देखें',
      'svc_queue': 'कतार स्थिति',
      'svc_queue_sub': 'लाइव प्रतीक्षा समय और नंबर',
      'svc_records': 'मेरे स्वास्थ्य रिकॉर्ड',
      'svc_records_sub': 'ABHA और सहमति-अधिकृत',
      'svc_rx': 'नुस्खे (Rx)',
      'svc_rx_sub': 'डॉक्टर Rx और दवा सलाह',
      'svc_lab': 'लैब रिपोर्ट',
      'svc_lab_sub': 'CBC, मलेरिया, जांच रिपोर्ट',
      'svc_referrals': 'रेफरल और फॉलो-अप',
      'svc_referrals_sub': 'विशेषज्ञ और नियमित जांच',
      'svc_teleconsult': 'टेलीकंसल्टेशन',
      'svc_teleconsult_sub': 'डॉक्टर के साथ WebRTC वीडियो कक्ष',
      'svc_medicines': 'निकटतम दवाइयाँ',
      'svc_medicines_sub': 'लाइव फार्मेसी स्टॉक और मूल्य',
      'svc_diagnostics': 'निकटतम डायग्नोस्टिक सेंटर',
      'svc_diagnostics_sub': 'लैब, जांच और टर्नअराउंड समय',
      'svc_emergency_assist': 'आपातकालीन सहायता',
      'svc_emergency_assist_sub': '108 एम्बुलेंस और आशा सतर्कता',
      'medicine_availability': 'दवा उपलब्धता',
      'medicine_availability_sub': 'निकटतम फार्मेसी में स्टॉक खोजें',
      'diagnostic_centres': 'निकटतम डायग्नोस्टिक सेंटर',
      'diagnostic_centres_sub': 'NABL लैब और PHC पैथोलॉजी',
      'check_medicine_stock': 'दवा स्टॉक जांचें',
      'find_diagnostic_centres': 'डायग्नोस्टिक सेंटर खोजें',
      'ai_safety_notice': 'AI-सहायता सुझाव केवल — निदान नहीं। लाइसेंस प्राप्त चिकित्सक द्वारा पुष्टि।',
      'appt_booked_snackbar': 'डॉ. राजेश शर्मा के साथ सुबह 10:30 बजे स्लॉट बुक हो गया।',
    },

    // -------------------------------------------------------------
    // TELUGU (te) — తెలుగు
    // -------------------------------------------------------------
    'te': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'పీహెచ్‌సీ ఆధారిత ఆరోగ్య సేవల వేదిక (మహారాష్ట్ర)',
      'switch_portal': 'పోర్టల్ మార్చండి',
      'emergency_sos': '108 అత్యవసర అంబులెన్స్ (SOS)',
      'logout': 'లాగ్ అవుట్',
      'language': 'భాష',
      'live_gps_chip': 'లైవ్ జీపీఎస్ సక్రియం',
      'status_live': 'లైవ్',

      'nav_patient_home': 'రోగి హోమ్',
      'nav_my_consultations': 'నా సంప్రదింపులు',
      'nav_hospital_referrals': 'ఆసుపత్రి రిఫరల్స్',
      'nav_voice_checker': 'వాయిస్ లక్షణాల తనిఖీ',
      'nav_opd_appointments': 'ఓపీడీ అపాయింట్‌మెంట్లు',
      'nav_teleconsultation': 'టెలికన్సల్టేషన్ (వీడియో)',
      'nav_emergency_alerts': 'అత్యవసర హెచ్చరికలు',
      'nav_clinical_kpi': 'క్లినికల్ విశ్లేషణలు',
      'nav_voice_symptoms': 'వాయిస్ లక్షణాలు నమోదు',
      'nav_patients_followups': 'రోగులు & ఫాలో-అప్స్',
      'nav_alerts_visits': 'గ్రామ హెచ్చరికలు',
      'nav_phc_overview': 'పీహెచ్‌సీ ఓపీడీ క్యూ',
      'nav_phc_analytics': 'జిల్లా ఆరోగ్య విశ్లేషణలు',
      'nav_phc_asha_network': 'ఆశా నెట్‌వర్క్',
      'nav_phc_doctors': 'వైద్య సిబ్బంది',
      'nav_pharmacy_dispense': 'మందుల పంపిణీ',
      'nav_pharmacy_inventory': 'మందుల స్టాక్',
      'nav_lab_orders': 'ల్యాబ్ పరీక్షలు',
      'nav_lab_tests': 'పరీక్షల జాబితా',

      'role_patient': 'రోగి పోర్టల్',
      'role_doctor': 'వైద్యుల పోర్టల్',
      'role_asha': 'ఆశా కార్యకర్త పోర్టల్',
      'role_phc_admin': 'పీహెచ్‌సీ పరిపాలన',
      'role_pharmacy': 'పీహెచ్‌సీ ఫార్మసీ',
      'role_lab': 'పీహెచ్‌సీ ల్యాబ్',

      'welcome_patient': 'స్వాగతం,',
      'live_gps_title': 'రోగి లైవ్ GPS స్థానం (మహారాష్ట్ర)',
      'gps_detected_label': 'గుర్తించబడిన GPS స్థానం',
      'gps_coordinates': 'కోఆర్డినేట్లు',
      'gps_accuracy': 'ఖచ్చితత్వం',
      'btn_fetch_live_gps': 'లైవ్ GPS పొందండి',
      'btn_switch_district': 'మహారాష్ట్ర జిల్లా మార్చండి',
      'gps_status_active': 'లైవ్ GPS ట్రాకింగ్ నడుస్తోంది',
      'gps_status_detecting': 'GPS గుర్తిస్తోంది...',
      'quick_actions': 'త్వరిత ఆరోగ్య సేవలు',
      'find_medicines': 'సమీప మందుల లభ్యత',
      'find_medicines_sub': 'శివాజీ నగర్ పీహెచ్‌సీ & జన్ ఔషధి స్టాక్',
      'book_lab_test': 'ల్యాబ్ టెస్ట్ బుక్ చేయండి',
      'book_lab_test_sub': 'NHM మహారాష్ట్ర కింద ఉచిత రక్త పరీక్షలు',
      'voice_ai_checker': 'AI వాయిస్ సింప్టమ్ చెకర్',
      'voice_ai_checker_sub': 'తెలుగు, హిందీ లేదా ఇంగ్లీషులో మాట్లాడండి',
      'call_teleconsult': 'వీడియో ద్వారా డాక్టర్‌ను సంప్రదించండి',
      'call_teleconsult_sub': 'డ్యూటీ మెడికల్ ఆఫీసర్‌తో లైవ్ సంప్రదింపు',
      'active_appointments': 'నా ఓపీడీ అపాయింట్‌మెంట్లు',
      'no_active_appointments': 'రాబోయే అపాయింట్‌మెంట్లు ఏవీ లేవు.',
      'book_opd_now': 'ఇప్పుడే ఓపీడీ బుక్ చేయండి',
      'medical_records': 'నా ABHA ఆరోగ్య రికార్డులు',
      'view_rx': 'డాక్టర్ ప్రిస్క్రిప్షన్ (Rx) చూడండి',
      'recent_vitals': 'ఇటీవలి వైటల్స్',
      'bp_label': 'రక్తపోటు (BP)',
      'pulse_label': 'పల్స్ (Pulse)',
      'spo2_label': 'ఆక్సిజన్ (SpO2)',
      'temp_label': 'శరీర ఉష్ణోగ్రత',

      'status_completed': 'పూర్తయింది',
      'status_pending': 'పెండింగ్',
      'status_emergency': 'అత్యవసరం',
      'status_urgent': 'అర్జెంట్',
      'status_routine': 'సాధారణం',
      'btn_refresh': 'రిఫ్రెష్',
      'btn_save': 'సేవ్ & సబ్మిట్',
      'btn_cancel': 'రద్దు చేయి',
      'btn_close': 'మూసివేయి',
      'btn_search': 'శోధించు',
      'filter_all': 'అన్నీ',
      'filter_pending': 'పెండింగ్',
      'filter_prescribed': 'మందులు రాసినవి',
      'filter_emergency': 'అత్యవసరం',
      'district_pune': 'పూణే',
      'district_mumbai': 'ముంబై',
      'district_nagpur': 'నాగ్‌పూర్',
      'district_nashik': 'నాసిక్',
      'district_aurangabad': 'ఛత్రపతి శంభాజీనగర్',
      'district_kolhapur': 'కొల్హాపూర్',
      'district_satara': 'సతారా',
      'district_thane': 'థానే',

      // Patient Service Cards
      'patient_services_title': 'అన్ని రోగి సేవలు',
      'nearby_healthcare_title': 'సమీప ఆరోగ్య సేవలు (మహారాష్ట్ర)',
      'svc_report_symptoms': 'లక్షణాలు నివేదించు',
      'svc_report_symptoms_sub': 'వ్రాత ఆధారిత క్లినికల్ తీసుకోవడం',
      'svc_voice_report': 'వాయిస్ రిపోర్ట్',
      'svc_voice_report_sub': 'Whisper AI తో మాట-నుండి-టెక్స్ట్',
      'svc_book_appt': 'అపాయింట్‌మెంట్ బుక్ చేయండి',
      'svc_book_appt_sub': 'శివాజీ నగర్ PHC లో OPD స్లాట్',
      'svc_my_appts': 'నా అపాయింట్‌మెంట్లు',
      'svc_my_appts_sub': 'రాబోయే సంప్రదింపులు చూడండి',
      'svc_queue': 'క్యూ స్థితి',
      'svc_queue_sub': 'లైవ్ వేచి ఉండే సమయం & సంఖ్య',
      'svc_records': 'నా ఆరోగ్య రికార్డులు',
      'svc_records_sub': 'ABHA & అనుమతి-అధికారం',
      'svc_rx': 'ప్రిస్క్రిప్షన్లు',
      'svc_rx_sub': 'డాక్టర్ Rx & మందుల సలహా',
      'svc_lab': 'ల్యాబ్ ఫలితాలు',
      'svc_lab_sub': 'CBC, మలేరియా, నిదాన నివేదికలు',
      'svc_referrals': 'రిఫరల్స్ & ఫాలో-అప్స్',
      'svc_referrals_sub': 'నిపుణుడు & క్రమం తనిఖీలు',
      'svc_teleconsult': 'టెలికన్సల్టేషన్',
      'svc_teleconsult_sub': 'డాక్టర్‌తో WebRTC వీడియో గది',
      'svc_medicines': 'సమీప మందులు',
      'svc_medicines_sub': 'లైవ్ ఫార్మసీ స్టాక్ & ధర',
      'svc_diagnostics': 'సమీప ల్యాబ్ సెంటర్లు',
      'svc_diagnostics_sub': 'ల్యాబ్లు, పరీక్షలు & సమయం',
      'svc_emergency_assist': 'అత్యవసర సహాయం',
      'svc_emergency_assist_sub': '108 డిస్పాచ్ & ఆశా హెచ్చరిక',
      'medicine_availability': 'మందుల లభ్యత',
      'medicine_availability_sub': 'సమీప ఫార్మసీలలో స్టాక్ కనుగొనండి',
      'diagnostic_centres': 'సమీప నిదాన కేంద్రాలు',
      'diagnostic_centres_sub': 'NABL ల్యాబ్లు & PHC పాథాలజీ',
      'check_medicine_stock': 'మందుల స్టాక్ తనిఖీ చేయండి',
      'find_diagnostic_centres': 'నిదాన కేంద్రాలు కనుగొనండి',
      'ai_safety_notice': 'AI-సహాయక సూచన మాత్రమే — నిదానం కాదు. లైసెన్స్ పొందిన వైద్యుడు ధృవీకరించారు.',
      'appt_booked_snackbar': 'డా. రాజేష్ శర్మతో ఉదయం 10:30కి స్లాట్ బుక్ అయింది.',
    },

    // -------------------------------------------------------------
    // TAMIL (ta) — தமிழ்
    // -------------------------------------------------------------
    'ta': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'ஆரம்ப சுகாதார நிலைய அணுகல் தளம் (மகாராஷ்டிரா)',
      'switch_portal': 'போர்ட்டலை மாற்று',
      'emergency_sos': '108 அவசர ஆம்புலன்ஸ் (SOS)',
      'logout': 'வெளியேறு',
      'language': 'மொழி',
      'live_gps_chip': 'நேரடி GPS செயலில் உள்ளது',
      'status_live': 'நேரலை',

      'nav_patient_home': 'நோயாளி முகப்பு',
      'nav_my_consultations': 'எனது ஆலோசனைகள்',
      'nav_hospital_referrals': 'மருத்துவமனை பரிந்துரைகள்',
      'nav_voice_checker': 'குரல் அறிகுறி சோதனையாளர்',
      'nav_opd_appointments': 'OPD முன்பதிவுகள்',
      'nav_teleconsultation': 'தொலைதூர ஆலோசனை (வீடியோ)',
      'nav_emergency_alerts': 'அவசர எச்சரிக்கைகள்',
      'nav_clinical_kpi': 'மருத்துவ பகுப்பாய்வு',
      'nav_voice_symptoms': 'குரல் அறிகுறிகள் பதிவு',
      'nav_patients_followups': 'நோயாளிகள் & பின்தொடர்தல்',
      'nav_alerts_visits': 'கிராம எச்சரிக்கைகள்',
      'nav_phc_overview': 'PHC வரிசை',
      'nav_phc_analytics': 'மாவட்ட பகுப்பாய்வு',
      'nav_phc_asha_network': 'ஆஷா நெட்வொர்க்',
      'nav_phc_doctors': 'மருத்துவ ஊழியர்கள்',
      'nav_pharmacy_dispense': 'மருந்து விநியோகம்',
      'nav_pharmacy_inventory': 'மருந்து இருப்பு',
      'nav_lab_orders': 'ஆய்வக சோதனைகள்',
      'nav_lab_tests': 'சோதனை பட்டியல்',

      'role_patient': 'நோயாளி போர்டல்',
      'role_doctor': 'மருத்துவர் போர்டல்',
      'role_asha': 'ஆஷா பணியாளர் போர்டல்',
      'role_phc_admin': 'PHC நிர்வாகம்',
      'role_pharmacy': 'PHC மருந்தகம்',
      'role_lab': 'PHC ஆய்வகம்',

      'welcome_patient': 'வரவேற்கிறோம்,',
      'live_gps_title': 'நோயாளி நேரடி GPS இடம் (மகாராஷ்டிரா)',
      'gps_detected_label': 'கண்டறியப்பட்ட GPS இடம்',
      'gps_coordinates': 'அமைவிடக் கூறுகள்',
      'gps_accuracy': 'துல்லியம்',
      'btn_fetch_live_gps': 'நேரடி GPS பெறு',
      'btn_switch_district': 'மகாராஷ்டிரா மாவட்டத்தை மாற்று',
      'gps_status_active': 'நேரடி GPS கண்காணிப்பு செயலில் உள்ளது',
      'gps_status_detecting': 'GPS கண்டறிகிறது...',
      'quick_actions': 'விரைவு சுகாதார சேவைகள்',
      'find_medicines': 'அருகிலுள்ள மருந்துகள்',
      'find_medicines_sub': 'சிவாஜி நகர் PHC மற்றும் ஜன் ஔஷதி இருப்பு',
      'book_lab_test': 'ஆய்வக பரிசோதனை முன்பதிவு',
      'book_lab_test_sub': 'NHM மகாராஷ்டிராவின் கீழ் இலவச இரத்த பரிசோதனை',
      'voice_ai_checker': 'AI குரல் அறிகுறி சோதனையாளர்',
      'voice_ai_checker_sub': 'தமிழ், இந்தி அல்லது ஆங்கிலத்தில் பேசவும்',
      'call_teleconsult': 'மருத்துவரிடம் வீடியோ ஆலோசனை',
      'call_teleconsult_sub': 'பணியில் உள்ள மருத்துவருடன் நேரடி தொடர்பு',
      'active_appointments': 'எனது OPD ஆலோசனைகள்',
      'no_active_appointments': 'வரவிருக்கும் முன்பதிவுகள் எதுவும் இல்லை.',
      'book_opd_now': 'இப்போதே OPD முன்பதிவு செய்யுங்கள்',
      'medical_records': 'எனது ABHA சுகாதார பதிவுகள்',
      'view_rx': 'மருத்துவர் மருந்துச் சீட்டு (Rx) காண்க',
      'recent_vitals': 'சமீபத்திய உடல் அளவீடுகள்',
      'bp_label': 'இரத்த அழுத்தம் (BP)',
      'pulse_label': 'நாடித்துடிப்பு (Pulse)',
      'spo2_label': 'ஆக்ஸிஜன் அளவு (SpO2)',
      'temp_label': 'உடல் வெப்பநிலை',

      'status_completed': 'முடிந்தது',
      'status_pending': 'நிலுவையில்',
      'status_emergency': 'அவசரம்',
      'status_urgent': 'முக்கியமானது',
      'status_routine': 'வழக்கமானது',
      'btn_refresh': 'புதுப்பி',
      'btn_save': 'சேமித்து சமர்ப்பி',
      'btn_cancel': 'ரத்துசெய்',
      'btn_close': 'மூடு',
      'btn_search': 'தேடு',
      'filter_all': 'அனைத்தும்',
      'filter_pending': 'நிலுவையில்',
      'filter_prescribed': 'பரிந்துரைக்கப்பட்டது',
      'filter_emergency': 'அவசரம்',
      'district_pune': 'புனே',
      'district_mumbai': 'மும்பை',
      'district_nagpur': 'நாக்பூர்',
      'district_nashik': 'நாசிக்',
      'district_aurangabad': 'சத்ரபதி சம்பாஜிநகர்',
      'district_kolhapur': 'கோலாப்பூர்',
      'district_satara': 'சதாரா',
      'district_thane': 'தானே',

      // Patient Service Cards
      'patient_services_title': 'அனைத்து நோயாளி சேவைகள்',
      'nearby_healthcare_title': 'அருகிலுள்ள சுகாதார சேவைகள் (மகாராஷ்டிரா)',
      'svc_report_symptoms': 'அறிகுறிகள் அறிக்கை',
      'svc_report_symptoms_sub': 'உரை-அடிப்படையிலான மருத்துவ உள்ளீடு',
      'svc_voice_report': 'குரல் அறிக்கை',
      'svc_voice_report_sub': 'Whisper AI மூலம் பேச்சு-முதல்-உரை',
      'svc_book_appt': 'சந்திப்பு முன்பதிவு',
      'svc_book_appt_sub': 'சிவாஜி நகர் PHC இல் OPD இடம்',
      'svc_my_appts': 'என் சந்திப்புகள்',
      'svc_my_appts_sub': 'வரவிருக்கும் ஆலோசனைகள்',
      'svc_queue': 'வரிசை நிலை',
      'svc_queue_sub': 'நேரடி காத்திருப்பு நேரம் & எண்',
      'svc_records': 'என் சுகாதார பதிவுகள்',
      'svc_records_sub': 'ABHA & அனுமதி-அங்கீகரிக்கப்பட்டது',
      'svc_rx': 'மருந்துச்சீட்டுகள்',
      'svc_rx_sub': 'மருத்துவர் Rx & மருந்து ஆலோசனை',
      'svc_lab': 'ஆய்வக முடிவுகள்',
      'svc_lab_sub': 'CBC, மலேரியா, நிதானிக்கும் அறிக்கைகள்',
      'svc_referrals': 'பரிந்துரைகள் & பின்தொடர்தல்',
      'svc_referrals_sub': 'நிபுணர் & வழக்கமான சோதனை',
      'svc_teleconsult': 'தொலைதூர ஆலோசனை',
      'svc_teleconsult_sub': 'மருத்துவருடன் WebRTC வீடியோ',
      'svc_medicines': 'அருகிலுள்ள மருந்துகள்',
      'svc_medicines_sub': 'நேரடி மருந்தக கையிருப்பு & விலை',
      'svc_diagnostics': 'அருகிலுள்ள ஆய்வக மையங்கள்',
      'svc_diagnostics_sub': 'ஆய்வகங்கள், சோதனைகள் & நேரம்',
      'svc_emergency_assist': 'அவசர உதவி',
      'svc_emergency_assist_sub': '108 அனுப்பல் & ஆஷா எச்சரிக்கை',
      'medicine_availability': 'மருந்து கிடைக்கும் தன்மை',
      'medicine_availability_sub': 'அருகிலுள்ள மருந்தகங்களில் கையிருப்பு',
      'diagnostic_centres': 'அருகிலுள்ள நோயறிதல் மையங்கள்',
      'diagnostic_centres_sub': 'NABL ஆய்வகங்கள் & PHC நோயியல்',
      'check_medicine_stock': 'மருந்து கையிருப்பு சரிபார்க்கவும்',
      'find_diagnostic_centres': 'நோயறிதல் மையங்கள் கண்டறியவும்',
      'ai_safety_notice': 'AI-உதவி ஆலோசனை மட்டுமே — நோய் கண்டறிவதில்லை. உரிமம் பெற்ற மருத்துவர் உறுதிப்படுத்துகிறார்.',
      'appt_booked_snackbar': 'டாக்டர் ராஜேஷ் ஷர்மாவுடன் காலை 10:30 மணிக்கு இடம் பதிவாகியது.',
    },

    // -------------------------------------------------------------
    // KANNADA (kn) — ಕನ್ನಡ
    // -------------------------------------------------------------
    'kn': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'ಪ್ರಾಥಮಿಕ ಆರೋಗ್ಯ ಕೇಂದ್ರ ಆಧಾರಿತ ವೇದಿಕೆ (ಮಹಾರಾಷ್ಟ್ರ)',
      'switch_portal': 'ಪೋರ್ಟಲ್ ಬದಲಾಯಿಸಿ',
      'emergency_sos': '108 ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್ (SOS)',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'language': 'ಭಾಷೆ',
      'live_gps_chip': 'ಲೈವ್ GPS ಸಕ್ರಿಯವಾಗಿದೆ',
      'status_live': 'ಲೈವ್',

      'nav_patient_home': 'ರೋಗಿಯ ಮುಖಪುಟ',
      'nav_my_consultations': 'ನನ್ನ ಸಮಾಲೋಚನೆಗಳು',
      'nav_hospital_referrals': 'ಆಸ್ಪತ್ರೆ ಉಲ್ಲೇಖಗಳು (ರೆಫರಲ್)',
      'nav_voice_checker': 'ಧ್ವನಿ ಲಕ್ಷಣ ಪರೀಕ್ಷಕ',
      'nav_opd_appointments': 'OPD ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
      'nav_teleconsultation': 'ಟೆಲಿಕನ್ಸಲ್ಟೇಶನ್ (ವೀಡಿಯೊ)',
      'nav_emergency_alerts': 'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
      'nav_clinical_kpi': 'ಕ್ಲಿನಿಕಲ್ ಅಂಕಿಅಂಶಗಳು',
      'nav_voice_symptoms': 'ಧ್ವನಿ ಲಕ್ಷಣ ದಾಖಲಿಸಿ',
      'nav_patients_followups': 'ರೋಗಿಗಳು ಮತ್ತು ಫಾಲೋ-ಅಪ್',
      'nav_alerts_visits': 'ಗ್ರಾಮ ಎಚ್ಚರಿಕೆಗಳು',
      'nav_phc_overview': 'PHC ಸರದಿ',
      'nav_phc_analytics': 'ಜಿಲ್ಲಾ ವಿಶ್ಲೇಷಣೆ',
      'nav_phc_asha_network': 'ಆಶಾ ನೆಟ್‌ವರ್ಕ್',
      'nav_phc_doctors': 'ವೈದ್ಯಕೀಯ ಸಿಬ್ಬಂದಿ',
      'nav_pharmacy_dispense': 'ಔಷಧ ವಿತರಣೆ',
      'nav_pharmacy_inventory': 'ಔಷಧ ದಾಸ್ತಾನು',
      'nav_lab_orders': 'ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು',
      'nav_lab_tests': 'ಪರೀಕ್ಷಾ ಕ್ಯಾಟಲಾಗ್',

      'role_patient': 'ರೋಗಿ ಪೋರ್ಟಲ್',
      'role_doctor': 'ವೈದ್ಯರ ಪೋರ್ಟಲ್',
      'role_asha': 'ಆಶಾ ಕಾರ್ಯಕರ್ತೆ ಪೋರ್ಟಲ್',
      'role_phc_admin': 'PHC ಆಡಳಿತ',
      'role_pharmacy': 'PHC ಔಷಧಾಲಯ',
      'role_lab': 'PHC ಪ್ರಯೋಗಾಲಯ',

      'welcome_patient': 'ಸ್ವಾಗತ,',
      'live_gps_title': 'ರೋಗಿಯ ಲೈವ್ GPS ಸ್ಥಳ (ಮಹಾರಾಷ್ಟ್ರ)',
      'gps_detected_label': 'ಗುರುತಿಸಲಾದ GPS ಸ್ಥಳ',
      'gps_coordinates': 'ಸ್ಥಳ ನಿರ್ದೇಶಾಂಕಗಳು',
      'gps_accuracy': 'ನಿಖರತೆ',
      'btn_fetch_live_gps': 'ಲೈವ್ GPS ಪಡೆಯಿರಿ',
      'btn_switch_district': 'ಮಹಾರಾಷ್ಟ್ರ ಜಿಲ್ಲೆ ಬದಲಾಯಿಸಿ',
      'gps_status_active': 'ಲೈವ್ GPS ಟ್ರ್ಯಾಕಿಂಗ್ ಸಕ್ರಿಯವಾಗಿದೆ',
      'gps_status_detecting': 'GPS ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
      'quick_actions': 'ತ್ವರಿತ ಆರೋಗ್ಯ ಸೇವೆಗಳು',
      'find_medicines': 'ಹತ್ತಿರದ ಔಷಧಿ ಲಭ್ಯತೆ',
      'find_medicines_sub': 'ಶಿವಾಜಿ ನಗರ PHC ಮತ್ತು ಜನೌಷಧಿ ದಾಸ್ತಾನು',
      'book_lab_test': 'ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆ ಬುಕ್ ಮಾಡಿ',
      'book_lab_test_sub': 'NHM ಮಹಾರಾಷ್ಟ್ರ ಅಡಿಯಲ್ಲಿ ಉಚಿತ ರಕ್ತ ಪರೀಕ್ಷೆಗಳು',
      'voice_ai_checker': 'AI ಧ್ವನಿ ಲಕ್ಷಣ ಪರೀಕ್ಷಕ',
      'voice_ai_checker_sub': 'ಕನ್ನಡ, ಹಿಂದಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ',
      'call_teleconsult': 'ವೀಡಿಯೊ ಮೂಲಕ ವೈದ್ಯರ ಸಮಾಲೋಚನೆ',
      'call_teleconsult_sub': 'ಕರ್ತವ್ಯದಲ್ಲಿರುವ ವೈದ್ಯರೊಂದಿಗೆ ನೇರ ಮಾತುಕತೆ',
      'active_appointments': 'ನನ್ನ OPD ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
      'no_active_appointments': 'ಯಾವುದೇ ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.',
      'book_opd_now': 'ಈಗಲೇ OPD ಬುಕ್ ಮಾಡಿ',
      'medical_records': 'ನನ್ನ ABHA ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
      'view_rx': 'ವೈದ್ಯರ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ (Rx) ನೋಡಿ',
      'recent_vitals': 'ಇತ್ತೀಚಿನ ವೈಟಲ್ಸ್',
      'bp_label': 'ರಕ್ತದೊತ್ತಡ (BP)',
      'pulse_label': 'ನಾಡಿಮಿಡಿತ (Pulse)',
      'spo2_label': 'ಆಮ್ಲಜನಕ (SpO2)',
      'temp_label': 'ದೇಹದ ಉಷ್ಣತೆ',

      'status_completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
      'status_pending': 'ಬಾಕಿ ಇದೆ',
      'status_emergency': 'ತುರ್ತು',
      'status_urgent': 'ಅತ್ಯಗತ್ಯ',
      'status_routine': 'ಸಾಮಾನ್ಯ',
      'btn_refresh': 'ರಿಫ್ರೆಶ್',
      'btn_save': 'ಉಳಿಸಿ ಮತ್ತು ಸಲ್ಲಿಸಿ',
      'btn_cancel': 'ರದ್ದುಮಾಡಿ',
      'btn_close': 'ಮುಚ್ಚಿ',
      'btn_search': 'ಹುಡುಕಿ',
      'filter_all': 'ಎಲ್ಲವೂ',
      'filter_pending': 'ಬಾಕಿ',
      'filter_prescribed': 'ಔಷಧ ಸೂಚಿಸಲಾಗಿದೆ',
      'filter_emergency': 'ತುರ್ತು',
      'district_pune': 'ಪುಣೆ',
      'district_mumbai': 'ಮುಂಬೈ',
      'district_nagpur': 'ನಾಗಪುರ',
      'district_nashik': 'ನಾಸಿಕ್',
      'district_aurangabad': 'ಛತ್ರಪತಿ ಸಂಭಾಜಿನಗರ',
      'district_kolhapur': 'ಕೊಲ್ಹಾಪುರ',
      'district_satara': 'ಸತಾರಾ',
      'district_thane': 'ಠಾಣೆ',

      // Patient Service Cards
      'patient_services_title': 'ಎಲ್ಲಾ ರೋಗಿ ಸೇವೆಗಳು',
      'nearby_healthcare_title': 'ಸಮೀಪದ ಆರೋಗ್ಯ ಸೇವೆಗಳು (ಮಹಾರಾಷ್ಟ್ರ)',
      'svc_report_symptoms': 'ಲಕ್ಷಣಗಳನ್ನು ವರದಿ ಮಾಡಿ',
      'svc_report_symptoms_sub': 'ಪಠ್ಯ-ಆಧಾರಿತ ಕ್ಲಿನಿಕಲ್ ಇನ್‌ಪುಟ್',
      'svc_voice_report': 'ಧ್ವನಿ ವರದಿ',
      'svc_voice_report_sub': 'Whisper AI ನೊಂದಿಗೆ ಮಾತು-ಮಾಡಿ-ಪಠ್ಯ',
      'svc_book_appt': 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ',
      'svc_book_appt_sub': 'ಶಿವಾಜಿ ನಗರ PHC ನಲ್ಲಿ OPD ಸ್ಲಾಟ್',
      'svc_my_appts': 'ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು',
      'svc_my_appts_sub': 'ಮುಂಬರುವ ಸಮಾಲೋಚನೆಗಳು',
      'svc_queue': 'ಸರದಿ ಸ್ಥಿತಿ',
      'svc_queue_sub': 'ಲೈವ್ ಕಾಯುವ ಸಮಯ & ಸಂಖ್ಯೆ',
      'svc_records': 'ನನ್ನ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
      'svc_records_sub': 'ABHA & ಒಪ್ಪಿಗೆ-ಅಧಿಕೃತ',
      'svc_rx': 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು',
      'svc_rx_sub': 'ವೈದ್ಯರ Rx & ಔಷಧ ಸಲಹೆ',
      'svc_lab': 'ಲ್ಯಾಬ್ ಫಲಿತಾಂಶಗಳು',
      'svc_lab_sub': 'CBC, ಮಲೇರಿಯಾ, ರೋಗ ನಿರ್ಣಯ ವರದಿಗಳು',
      'svc_referrals': 'ರೆಫರಲ್‌ಗಳು & ಫಾಲೋ-ಅಪ್‌ಗಳು',
      'svc_referrals_sub': 'ತಜ್ಞ & ನಿಯಮಿತ ಪರೀಕ್ಷೆಗಳು',
      'svc_teleconsult': 'ಟೆಲಿಕನ್ಸಲ್ಟೇಶನ್',
      'svc_teleconsult_sub': 'ವೈದ್ಯರೊಂದಿಗೆ WebRTC ವೀಡಿಯೊ ಕೊಠಡಿ',
      'svc_medicines': 'ಸಮೀಪದ ಔಷಧಿಗಳು',
      'svc_medicines_sub': 'ಲೈವ್ ಫಾರ್ಮಸಿ ಸ್ಟಾಕ್ & ಬೆಲೆ',
      'svc_diagnostics': 'ಸಮೀಪದ ಡಯಾಗ್ನೋಸ್ಟಿಕ್ ಕೇಂದ್ರಗಳು',
      'svc_diagnostics_sub': 'ಲ್ಯಾಬ್‌ಗಳು, ಪರೀಕ್ಷೆಗಳು & ಸಮಯ',
      'svc_emergency_assist': 'ತುರ್ತು ಸಹಾಯ',
      'svc_emergency_assist_sub': '108 ಡಿಸ್ಪ್ಯಾಚ್ & ಆಶಾ ಎಚ್ಚರಿಕೆ',
      'medicine_availability': 'ಔಷಧ ಲಭ್ಯತೆ',
      'medicine_availability_sub': 'ಸಮೀಪದ ಫಾರ್ಮಸಿಗಳಲ್ಲಿ ಸ್ಟಾಕ್ ಕಂಡುಹಿಡಿಯಿರಿ',
      'diagnostic_centres': 'ಸಮೀಪದ ರೋಗ ನಿರ್ಣಯ ಕೇಂದ್ರಗಳು',
      'diagnostic_centres_sub': 'NABL ಲ್ಯಾಬ್‌ಗಳು & PHC ರೋಗಶಾಸ್ತ್ರ',
      'check_medicine_stock': 'ಔಷಧ ಸ್ಟಾಕ್ ಪರಿಶೀಲಿಸಿ',
      'find_diagnostic_centres': 'ರೋಗ ನಿರ್ಣಯ ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಿ',
      'ai_safety_notice': 'AI-ಸಹಾಯಿತ ಸೂಚನೆ ಮಾತ್ರ — ರೋಗ ನಿರ್ಣಯ ಮಾಡುವುದಿಲ್ಲ. ಪರವಾನಗಿ ಪಡೆದ ವೈದ್ಯರಿಂದ ದೃಢಪಡಿಸಲಾಗಿದೆ.',
      'appt_booked_snackbar': 'ಡಾ. ರಾಜೇಶ್ ಶರ್ಮಾ ಅವರೊಂದಿಗೆ ಬೆಳಿಗ್ಗೆ 10:30 ಕ್ಕೆ ಸ್ಲಾಟ್ ಬುಕ್ ಆಗಿದೆ.',
    },

    // -------------------------------------------------------------
    // GUJARATI (gu) — ગુજરાતી
    // -------------------------------------------------------------
    'gu': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'પ્રાથમિક આરોગ્ય કેન્દ્ર આધારિત પ્લેટફોર્મ (મહારાષ્ટ્ર)',
      'switch_portal': 'પોર્ટલ બદલો',
      'emergency_sos': '108 ઇમરજન્સી એમ્બ્યુલન્સ (SOS)',
      'logout': 'લૉગ આઉટ',
      'language': 'ભાષા',
      'live_gps_chip': 'લાઈવ GPS સક્રિય',
      'status_live': 'લાઈવ',

      'nav_patient_home': 'દર્દી હોમ',
      'nav_my_consultations': 'મારી સલાહ',
      'nav_hospital_referrals': 'હોસ્પિટલ રેફરલ',
      'nav_voice_checker': 'વોઇસ લક્ષણ તપાસક',
      'nav_opd_appointments': 'OPD એપોઇન્ટમેન્ટ્સ',
      'nav_teleconsultation': 'ટેલિકન્સલ્ટેશન (વીડિયો)',
      'nav_emergency_alerts': 'ઇમરજન્સી એલર્ટ્સ',
      'nav_clinical_kpi': 'ક્લિનિકલ આંકડા',
      'nav_voice_symptoms': 'અવાજથી લક્ષણો નોંધો',
      'nav_patients_followups': 'દર્દીઓ અને ફોલો-અપ',
      'nav_alerts_visits': 'ગામ એલર્ટ્સ',
      'nav_phc_overview': 'PHC કતાર',
      'nav_phc_analytics': 'જિલ્લા વિશ્લેષણ',
      'nav_phc_asha_network': 'આશા નેટવર્ક',
      'nav_phc_doctors': 'તબીબી સ્ટાફ',
      'nav_pharmacy_dispense': 'દવા વિતરણ',
      'nav_pharmacy_inventory': 'દવા સ્ટોક',
      'nav_lab_orders': 'લેબ પરીક્ષણો',
      'nav_lab_tests': 'પરીક્ષણ સૂચિ',

      'role_patient': 'દર્દી પોર્ટલ',
      'role_doctor': 'ડૉક્ટર પોર્ટલ',
      'role_asha': 'આશા વર્કર પોર્ટલ',
      'role_phc_admin': 'PHC વહીવટ',
      'role_pharmacy': 'PHC ફાર્મસી',
      'role_lab': 'PHC લેબોરેટરી',

      'welcome_patient': 'સ્વાગત છે,',
      'live_gps_title': 'દર્દીનું લાઈવ GPS લોકેશન (મહારાષ્ટ્ર)',
      'gps_detected_label': 'શોધાયેલ GPS સ્થાન',
      'gps_coordinates': 'કોઓર્ડિનેટ્સ',
      'gps_accuracy': 'ચોકસાઈ',
      'btn_fetch_live_gps': 'લાઈવ GPS મેળવો',
      'btn_switch_district': 'મહારાષ્ટ્ર જિલ્લો બદલો',
      'gps_status_active': 'લાઈવ GPS ટ્રેકિંગ સક્રિય છે',
      'gps_status_detecting': 'GPS શોધાઈ રહ્યું છે...',
      'quick_actions': 'ઝડપી આરોગ્ય સેવાઓ',
      'find_medicines': 'નજીકની દવાઓ શોધો',
      'find_medicines_sub': 'શિવાજી નગર PHC અને જન ઔષધિ સ્ટોક',
      'book_lab_test': 'લેબ ટેસ્ટ બુક કરો',
      'book_lab_test_sub': 'NHM મહારાષ્ટ્ર હેઠળ મફત રક્ત પરીક્ષણ',
      'voice_ai_checker': 'AI વોઇસ લક્ષણ તપાસક',
      'voice_ai_checker_sub': 'ગુજરાતી, હિન્દી અથવા અંગ્રેજીમાં બોલો',
      'call_teleconsult': 'ડૉક્ટર સાથે વીડિયો પરામર્શ',
      'call_teleconsult_sub': 'ઑન-ડ્યુટી મેડિકલ ઑફિસર સાથે સીધી વાત',
      'active_appointments': 'મારી OPD એપોઇન્ટમેન્ટ્સ',
      'no_active_appointments': 'કોઈ આગામી એપોઇન્ટમેન્ટ નથી.',
      'book_opd_now': 'હમણાં જ OPD બુક કરો',
      'medical_records': 'મારા ABHA હેલ્થ રેકોર્ડ્સ',
      'view_rx': 'ડૉક્ટરનું પ્રિસ્ક્રિપ્શન (Rx) જુઓ',
      'recent_vitals': 'તાજેતરના વાઇટલ્સ',
      'bp_label': 'બ્લડ પ્રેશર (BP)',
      'pulse_label': 'પલ્સ (Pulse)',
      'spo2_label': 'ઓક્સિજન (SpO2)',
      'temp_label': 'શરીરનું તાપમાન',

      'status_completed': 'પૂર્ણ થયું',
      'status_pending': 'બાકી',
      'status_emergency': 'ઇમરજન્સી',
      'status_urgent': 'તાકીદનું',
      'status_routine': 'સામાન્ય',
      'btn_refresh': 'રીફ્રેશ',
      'btn_save': 'સાચવો અને સબમિટ કરો',
      'btn_cancel': 'રદ કરો',
      'btn_close': 'બંધ કરો',
      'btn_search': 'શોધો',
      'filter_all': 'બધા',
      'filter_pending': 'બાકી',
      'filter_prescribed': 'દવા લખાયેલ',
      'filter_emergency': 'ઇમરજન્સી',
      'district_pune': 'પુણે',
      'district_mumbai': 'મુંબઈ',
      'district_nagpur': 'નાગપુર',
      'district_nashik': 'નાસિક',
      'district_aurangabad': 'છત્રપતિ સંભાજીનગર',
      'district_kolhapur': 'કોલ્હાપુર',
      'district_satara': 'સાતારા',
      'district_thane': 'થાણે',

      // Patient Service Cards
      'patient_services_title': 'તમામ દર્દી સેવાઓ',
      'nearby_healthcare_title': 'નજીકની સ્વાસ્થ્ય સેવાઓ (મહારાષ્ટ્ર)',
      'svc_report_symptoms': 'લક્ષણો જણાવો',
      'svc_report_symptoms_sub': 'ટેક્સ્ટ-આધારિત ક્લિનિકલ ઇનટેક',
      'svc_voice_report': 'વૉઇસ રિપોર્ટ',
      'svc_voice_report_sub': 'Whisper AI સાથે બોલ-થી-ટેક્સ્ટ',
      'svc_book_appt': 'એપોઇન્ટમેન્ટ બુક કરો',
      'svc_book_appt_sub': 'શિવાજી નગર PHC ખાતે OPD સ્લોટ',
      'svc_my_appts': 'મારી એપોઇન્ટમેન્ટ',
      'svc_my_appts_sub': 'આગામી સલાહ-મસલત જુઓ',
      'svc_queue': 'કતાર સ્થિતિ',
      'svc_queue_sub': 'લાઈવ રાહ સમય અને નંબર',
      'svc_records': 'મારા સ્વાસ્થ્ય રેકોર્ડ',
      'svc_records_sub': 'ABHA અને સંમતિ-અધિકૃત',
      'svc_rx': 'પ્રિસ્ક્રિપ્શન',
      'svc_rx_sub': 'ડૉક્ટર Rx અને દવા સલાહ',
      'svc_lab': 'લેબ પરિણામો',
      'svc_lab_sub': 'CBC, મેલેરિયા, નિદાન અહેવાલ',
      'svc_referrals': 'રેફરલ અને ફોલો-અપ',
      'svc_referrals_sub': 'નિષ્ણાત અને નિયમિત તપાસ',
      'svc_teleconsult': 'ટેલિકન્સલ્ટેશન',
      'svc_teleconsult_sub': 'ડૉક્ટર સાથે WebRTC વીડિયો',
      'svc_medicines': 'નજીકની દવાઓ',
      'svc_medicines_sub': 'લાઈવ ફાર્મસી સ્ટોક અને ભાવ',
      'svc_diagnostics': 'નજીકના ડાયગ્નોસ્ટિક સેન્ટર',
      'svc_diagnostics_sub': 'લેબ, પરીક્ષણ અને ટર્નઅરાઉન્ડ સમય',
      'svc_emergency_assist': 'ઇમરજન્સી સહાય',
      'svc_emergency_assist_sub': '108 ડિસ્પેચ અને આશા સતર્કતા',
      'medicine_availability': 'દવા ઉપલબ્ધતા',
      'medicine_availability_sub': 'નજીકની ફાર્મસીઓમાં સ્ટોક',
      'diagnostic_centres': 'નજીકના ડાયગ્નોસ્ટિક સેન્ટર',
      'diagnostic_centres_sub': 'NABL લેબ અને PHC પેથોલોજી',
      'check_medicine_stock': 'દવા સ્ટોક તપાસો',
      'find_diagnostic_centres': 'ડાયગ્નોસ્ટિક સેન્ટર શોધો',
      'ai_safety_notice': 'AI-સহાયિત સૂચન માત્ર — નિદાન નહીં. લાઇસન્સ ધારક ચિકિત્સક દ્વારા પુષ્ટિ.',
      'appt_booked_snackbar': 'ડૉ. રાજેશ શર્મા સાથે સવારે 10:30 વાગ્યે સ્લૉટ બુક થઈ ગઈ.',
    },

    // -------------------------------------------------------------
    // BENGALI (bn) — বাংলা
    // -------------------------------------------------------------
    'bn': {
      'platform_title': 'SwasthyaSetu',
      'platform_subtitle': 'প্রাথমিক স্বাস্থ্য কেন্দ্র-ভিত্তিক স্বাস্থ্য পরিষেবা মঞ্চ (মহারাষ্ট্র)',
      'switch_portal': 'পোর্টাল পরিবর্তন করুন',
      'emergency_sos': '১০৮ জরুরি অ্যাম্বুলেন্স (SOS)',
      'logout': 'লগ আউট',
      'language': 'ভাষা',
      'live_gps_chip': 'লাইভ GPS অবস্থান সক্রিয়',
      'status_live': 'লাইভ',

      'nav_patient_home': 'রোগীর হোম',
      'nav_my_consultations': 'আমার পরামর্শ',
      'nav_hospital_referrals': 'হাসপাতাল রেফারেল',
      'nav_voice_checker': 'ভয়েস লক্ষণ পরীক্ষক',
      'nav_opd_appointments': 'OPD অ্যাপয়েন্টমেন্ট',
      'nav_teleconsultation': 'টেলিকনসালটেশন (ভিডিও)',
      'nav_emergency_alerts': 'জরুরি সতর্কতা',
      'nav_clinical_kpi': 'ক্লিনিকাল পরিসংখ্যান',
      'nav_voice_symptoms': 'ভয়েস লক্ষণ রেকর্ড করুন',
      'nav_patients_followups': 'রোগী ও ফলো-আপ',
      'nav_alerts_visits': 'গ্রামের সতর্কতা',
      'nav_phc_overview': 'PHC সারি',
      'nav_phc_analytics': 'জেলা স্বাস্থ্য বিশ্লেষণ',
      'nav_phc_asha_network': 'আশা নেটওয়ার্ক',
      'nav_phc_doctors': 'চিকিৎসা কর্মী',
      'nav_pharmacy_dispense': 'ওষুধ বিতরণ',
      'nav_pharmacy_inventory': 'ওষুধের স্টক',
      'nav_lab_orders': 'ল্যাব পরীক্ষা',
      'nav_lab_tests': 'পরীক্ষার তালিকা',

      'role_patient': 'রোগী পোর্টাল',
      'role_doctor': 'ডাক্তার পোর্টাল',
      'role_asha': 'আশা কর্মী পোর্টাল',
      'role_phc_admin': 'PHC প্রশাসন',
      'role_pharmacy': 'PHC ফার্মেসি',
      'role_lab': 'PHC ডায়াগনস্টিক ল্যাব',

      'welcome_patient': 'স্বাগতম,',
      'live_gps_title': 'রোগীর লাইভ GPS অবস্থান (মহারাষ্ট্র)',
      'gps_detected_label': 'সনাক্তকৃত GPS অবস্থান',
      'gps_coordinates': 'স্থানাঙ্ক',
      'gps_accuracy': 'সঠিকতা',
      'btn_fetch_live_gps': 'লাইভ GPS সনাক্ত করুন',
      'btn_switch_district': 'মহারাষ্ট্র জেলা পরিবর্তন করুন',
      'gps_status_active': 'লাইভ GPS ট্র্যাকিং সক্রিয় রয়েছে',
      'gps_status_detecting': 'ডিভাইস GPS অনুসন্ধান করছে...',
      'quick_actions': 'দ্রুত স্বাস্থ্য পরিষেবা',
      'find_medicines': 'নিকটস্থ ওষুধ খুঁজুন',
      'find_medicines_sub': 'শিবাজী নগর PHC ও জন ঔষধি স্টক',
      'book_lab_test': 'ডায়াগনস্টিক টেস্ট বুক করুন',
      'book_lab_test_sub': 'NHM মহারাষ্ট্রের অধীনে বিনামূল্যে রক্ত পরীক্ষা',
      'voice_ai_checker': 'এআই ভয়েস লক্ষণ পরীক্ষক',
      'voice_ai_checker_sub': 'বাংলা, হিন্দি বা ইংরেজিতে বলুন',
      'call_teleconsult': 'ভিডিওর মাধ্যমে ডাক্তারের পরামর্শ',
      'call_teleconsult_sub': 'অন-ডিউটি মেডিকেল অফিসারের সাথে সরাসরি কথা',
      'active_appointments': 'আমার OPD অ্যাপয়েন্টমেন্ট',
      'no_active_appointments': 'কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই।',
      'book_opd_now': 'এখনই OPD বুক করুন',
      'medical_records': 'আমার ABHA স্বাস্থ্য রেকর্ড',
      'view_rx': 'ডাক্তারের প্রেসক্রিপশন (Rx) দেখুন',
      'recent_vitals': 'সাম্প্রতিক ভাইটালস',
      'bp_label': 'রক্তচাপ (BP)',
      'pulse_label': 'নাড়ির স্পন্দন (Pulse)',
      'spo2_label': 'অক্সিজেন স্তর (SpO2)',
      'temp_label': 'শরীরের তাপমাত্রা',

      'status_completed': 'সম্পন্ন',
      'status_pending': 'মুলতুবি',
      'status_emergency': 'জরুরি',
      'status_urgent': 'জরুরি প্রয়োজন',
      'status_routine': 'নিয়মিত',
      'btn_refresh': 'রিফ্রেশ',
      'btn_save': 'সংরক্ষণ ও জমা দিন',
      'btn_cancel': 'বাতিল',
      'btn_close': 'বন্ধ করুন',
      'btn_search': 'অনুসন্ধান',
      'filter_all': 'সমস্ত',
      'filter_pending': 'মুলতুবি',
      'filter_prescribed': 'প্রেসক্রিপশন দেওয়া',
      'filter_emergency': 'জরুরি',
      'district_pune': 'পুনে',
      'district_mumbai': 'মুম্বাই',
      'district_nagpur': 'নাগপুর',
      'district_nashik': 'নাসিক',
      'district_aurangabad': 'ছত্রপতি সম্ভাজিনগর',
      'district_kolhapur': 'কোলহাপুর',
      'district_satara': 'সাতারা',
      'district_thane': 'থানে',

      // Patient Service Cards
      'patient_services_title': 'সমস্ত রোগী সেবা',
      'nearby_healthcare_title': 'নিকটস্থ স্বাস্থ্যসেবা (মহারাষ্ট্র)',
      'svc_report_symptoms': 'লক্ষণ রিপোর্ট করুন',
      'svc_report_symptoms_sub': 'টেক্সট-ভিত্তিক ক্লিনিকাল ইনটেক',
      'svc_voice_report': 'ভয়েস রিপোর্ট',
      'svc_voice_report_sub': 'Whisper AI দিয়ে কথা-থেকে-পাঠ',
      'svc_book_appt': 'অ্যাপয়েন্টমেন্ট বুক করুন',
      'svc_book_appt_sub': 'শিবাজী নগর PHC-তে OPD স্লট',
      'svc_my_appts': 'আমার অ্যাপয়েন্টমেন্ট',
      'svc_my_appts_sub': 'আগামী পরামর্শ দেখুন',
      'svc_queue': 'কিউ স্ট্যাটাস',
      'svc_queue_sub': 'লাইভ অপেক্ষার সময় ও নম্বর',
      'svc_records': 'আমার স্বাস্থ্য রেকর্ড',
      'svc_records_sub': 'ABHA ও সম্মতি-অনুমোদিত',
      'svc_rx': 'প্রেসক্রিপশন',
      'svc_rx_sub': 'ডাক্তার Rx ও ওষুধ পরামর্শ',
      'svc_lab': 'ল্যাব ফলাফল',
      'svc_lab_sub': 'CBC, ম্যালেরিয়া, ডায়াগনস্টিক রিপোর্ট',
      'svc_referrals': 'রেফারেল ও ফলো-আপ',
      'svc_referrals_sub': 'বিশেষজ্ঞ ও নিয়মিত পরীক্ষা',
      'svc_teleconsult': 'টেলিকনসালটেশন',
      'svc_teleconsult_sub': 'ডাক্তারের সাথে WebRTC ভিডিও',
      'svc_medicines': 'নিকটস্থ ওষুধ',
      'svc_medicines_sub': 'লাইভ ফার্মেসি স্টক ও মূল্য',
      'svc_diagnostics': 'নিকটস্থ ডায়াগনস্টিক সেন্টার',
      'svc_diagnostics_sub': 'ল্যাব, পরীক্ষা ও টার্নঅ্যারাউন্ড সময়',
      'svc_emergency_assist': 'জরুরি সহায়তা',
      'svc_emergency_assist_sub': '108 ডিসপ্যাচ ও আশা সতর্কতা',
      'medicine_availability': 'ওষুধ প্রাপ্যতা',
      'medicine_availability_sub': 'নিকটস্থ ফার্মেসিতে স্টক খুঁজুন',
      'diagnostic_centres': 'নিকটস্থ ডায়াগনস্টিক কেন্দ্র',
      'diagnostic_centres_sub': 'NABL ল্যাব ও PHC প্যাথলজি',
      'check_medicine_stock': 'ওষুধ স্টক পরীক্ষা করুন',
      'find_diagnostic_centres': 'ডায়াগনস্টিক কেন্দ্র খুঁজুন',
      'ai_safety_notice': 'AI-সহায়তা পরামর্শ শুধুমাত্র — রোগ নির্ণয় নয়। লাইসেন্সধারী চিকিৎসক দ্বারা নিশ্চিত।',
      'appt_booked_snackbar': 'ডা. রাজেশ শর্মার সাথে সকাল ১০:৩০-এ স্লট বুক হয়েছে।',
    },
  };
}
